### ISSUE TITLE
Estruturar o diretório do projeto

### ISSUE THREAD

**Issue by JoaoVitor20151134010701** [JoaoVitor20151134010701/MeuProjeto#1]
#Organizar pastas

** organizar pastar do projeto para concentrar os arquivos que são logicamente relacionados **

**Comment by JoaoVitor20151134010701** [comment]
FEITO COM SUCESS !

**Comment by fpenha** [comment]
organizar a estrutura de diretório.

**Comment by JoaoVitor20151134010701** [comment]
Já foi concluído !
